### ISSUE TITLE
Compatibility with legacy editor

### ISSUE THREAD

**Issue by olivia530** [liamcain/obsidian-creases#11]
I just installed the latest version of Creases via BRAT and have been testing it out. Is it designed to be compatible with Live Preview, the legacy editor, or both? I am currently using the legacy editor, and have found that the plugin commands only run when I am in editing view as opposed to reading view. 

Also, none of Creases' commands show up in the command palette—which means the only way for me to run any commands with this plugin is to go into the hotkeys section of Obsidian's settings, set a hotkey for the command I want to run, and then press that hotkey (while making sure I am in editing mode). I like the convenience of hotkeys, but it would also be great to run commands straight from the command palette.

**Comment by liamcain** [comment]
Hi Olivia, I just released v0.4.2 which should improve compatibility with the Legacy editor.

As for why the creases commands aren't showing up, some of them are situational. The `Toggle fold for H1/H2/H3...` commands only appear if there is a heading matching that level in the document. If _none_ of the commands are showing up, there might be an issue with loading the plugin. If that's the case, could you check in the Developer Tools to see if there's an error?

---

To view the Developer Tools, press Ctrl-Shift-I on Windows/Linux or Cmd-Opt-I on MacOS; on MacOS alternatively View › Toggle Developer Tools)

**Comment by olivia530** [comment]
Thanks for the fast response. I updated the plugin, but it behaves the same. Only works in editing mode, and none of the commands show up in the command palette. I checked the Developer Tools, but there didn't seem to be anything there related to Creases.

**Comment by liamcain** [comment]
Oh whoops, sorry about that!! I live in Live Preview so much these days that I forgot it might be useful to toggle the folds from within Reading mode. I just made another release (0.4.3) which will enable the `Toggle folds for h1...h6" command as well as "Fold along creases." The "toggle crease" command will be editing mode-only since it looks at the cursor position to see where to crease.

**Comment by olivia530** [comment]
Installed the update and it works perfectly, thanks!
