### ISSUE TITLE
FR: make heading always folded

### ISSUE THREAD

**Issue by imeed166** [liamcain/obsidian-creases#15]
It would be amazing if we could write `%% folded %%` and have the heading always fold whenever we open the file, regardless of its previous state.

**Comment by liamcain** [comment]
I like the idea, I'm just not sure I want to introduce an extra syntax for always folded creases. I think `%% fold %%` is already confusing enough for new users that this will just add too much complexity. So for now I added a setting to configure how creases work:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/693981/159130936-209485ae-b074-4cad-95ed-904ce56f31bc.png">

I think this solves the primary use case for having headings folded so I'll mark this as complete for now. Feel free to reopen if you feel like there's a valid use case that requires having both `%% fold %%` and `%% folded %%` though!

**Comment by imeed166** [comment]
Thank you, this solves my problem. 

I just want to add my opinion about `crease` being confusing to users. I think, 3 formats like this would be easier to understand :
- `%% save %%` to save current fold state
- `%% fold %%` to always fold
- `%% unfold %%` to always unfold

**Comment by liamcain** [comment]
I was thinking of doing something similar to how Callouts work in obsidian. So `%% fold %%`, `%% fold+ %%`, and %% fold- %%`. But it adds a lot of complexity to the plugin and I'm still not sure it's needed.

**Comment by imeed166** [comment]
Yes, that would be much needed. I can think of many use cases that would benefit from these 3 format, let's say you have 3 files :
- in first file, you want all headings to fold
- in second file, you want all headings to unfold
- in third file, you want some headings to fold, and headings to unfold

**Comment by imeed166** [comment]
Thinking about it, the second use case in how obsidian works without this plugin. So maybe you're right, and we only need `%% fold %%`, `%% fold+ %%` (+ being always folded).

**Comment by imeed166** [comment]
Sorry for talking too much, but now that `always fold` is implemented. I don't even know why anyone would use save current fold state. If they want to fold, they would add the `%% fold %%` and if they don't, they'd leave it empty.

**Comment by liamcain** [comment]
> Sorry for talking too much, but now that always fold is implemented. I don't even know why anyone would use save current fold state. If they want to fold, they would add the %% fold %% and if they don't, they'd leave it empty.

Yeah, exactly. I think this makes the most sense, I just didn't make it the default since it's a bit more intrusive. But I agree, users likely expect creases to always be folded.

**Comment by cansar** [comment]
I just want to say that I LOVE the new setting (and whole plugin). IMO it makes Daily notes way more useful and much easier to quickly revisit and learn from Daily notes pages.
