### ISSUE TITLE
FR: keep outline folding in sync with note folding

### ISSUE THREAD

**Issue by etiennepellegrini** [liamcain/obsidian-creases#19]
Being able to keep the outline's folding synced with the note would be great.

I can think of a couple different ways to control the sync that would be very practical:
- a global `keep folding synchronized` flag (and associated command to toggle it)
- new commands which allow to `copy note folding to outline` or `copy outline folding to note`, which could be used when the sync is off

**Comment by liamcain** [comment]
In v0.5.0, folds in the editor will now sync to the outline view (unidirectional).

**Comment by liamcain** [comment]
Just added bidirectional syncing in v0.6.3 so I will mark this as complete. Let me know if there are any issues.
