### ISSUE TITLE
Folding not honored in transcludes

### ISSUE THREAD

**Issue by ankushg** [liamcain/obsidian-creases#4]
Folding doesn't seem to be honored in transcludes.

On note `A` I have an H2 with nested H3s, some of which are folded. The H3s show as folded on note `A` (edit and preview mode).

When I transclude `![[A#H2]]` on note `B`, every H3 is visible by default in the preview.

**Comment by liamcain** [comment]
Going to close these issues since Creases has been entirely rewritten in v0.3.X and works a lot differently.

Feel free to try out the new version and make suggestions though!
