### ISSUE TITLE
How can I see the level of the Titles/Headers? 

### ISSUE THREAD

**Issue by bav2653** [liamcain/obsidian-creases#49]
![8f47a53a-acf7-42f8-9850-ed0b4e17c88f](https://github.com/liamcain/obsidian-creases/assets/106904115/0db59d04-ce53-4482-830b-71c7d77016de)

There is this option, but I don't like it.
https://forum.obsidian.md/t/css-for-showing-heading-levels-in-gutter/72244/2

**Comment by bav2653** [comment]
I decided to use the "Blue Topaz" theme.

**Comment by liamcain** [comment]
That's a different plugin: [Lapel](https://github.com/liamcain/obsidian-lapel)
