### ISSUE TITLE
First section always folded??

### ISSUE THREAD

**Issue by lebigot** [liamcain/obsidian-creases#56]
Here is a small bug report:

Anytime I open a certain file, its first section (which starts at the top-most line) always starts _folded_, which is annoying.

Just in case this is useful:
- This section is _not folded_, when I close Obsidian.
- This first section is _not creased_ (no `%%…%%` mark).
- This first section contains a bit of text and some tasks (```) block from the Tasks plugin, which may take some time (less than a second) to display. Maybe this somehow interferes with Creases??

Thanks!

**Comment by liamcain** [comment]
I think this is a bug in Obsidian, should be fixed in the next release.
