### ISSUE TITLE
FR: Unfold by Heading Level & commands for specific heading levels

### ISSUE THREAD

**Issue by chrisgrieser** [liamcain/obsidian-creases#9]
- currently, we can fold by heading, but *unfolding* headings by level might be useful as well.
- how about one separate commend per heading level for quicker access?

**Comment by liamcain** [comment]
> how about one separate commend per heading level for quicker access?

Yeah, I debated this. Wasn't sure if there should be a suggester + separate commands for each heading level since I do get annoyed at plugins that flood the command palette with too many options. But I think to make it hotkey-able, it makes sense.

> currently, we can fold by heading, but unfolding headings by level might be useful as well.

Do you the current command should just be switched to **Toggle**? Or should they be separate commands?

**Comment by chrisgrieser** [comment]
> I do get annoyed at plugins that flood the command palette with too many options.

[There is a plugin for that.](https://obsidian.md/plugins?id=obsidian-command-palette-minus-plugin) 😉

**Comment by liamcain** [comment]
> I personally would prefer a toggle – with two commands, and one command per heading level, this would be 12 hotkeys, and I do not have enough hotkeys free for that 😅

Yeah, I'm thinking the behavior will be "is the first heading of this level folded?"
- first heading is folded: unfold all headings of that level
- first heading is unfolded: fold all headings of that level.

If the first fold doesn't match the state you want to be in (folded/unfolded) you can just use run the command a second time.

I think that that's advantageous to adding more commands.

**Comment by chrisgrieser** [comment]
That toggling method sounds good to me! :)

**Comment by liamcain** [comment]
Okay, I just released v0.3.1 which includes separate commands to toggle each fold level.
